komendrinken/achievements/urls.py
from django.conf.urls import url

from achievements import views

urlpatterns = [
    url(r'^$', views.client, name="home"),
    url(r'^signup/$', views.signUp, name='handleSignUp'),
    url(r'^vote/(?P<game_id>\d+)/$', views.vote, name='handleVote'),
    
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^game/new/(?P<achievement_id>\d+)$', views.newGame, name='newGame'),
    url(r'^game/voting/(?P<game_id>\d+)$', views.startVoting, name='startVoting'),
    url(r'^game/schedule/(?P<game_id>\d+)$', views.scheduleVoting, name='scheduleVoting'),
    url(r'^game/start/(?P<game_id>\d+)$', views.startGame, name='startGame'),
    url(r'^game/end/(?P<game_id>\d+)$', views.endGame, name='endGame'),
    
    url(r'^presentation/$', views.presentation, name='presentation'),
]

komendrinken/komendrinken/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView

# Error pages
handler401 = 'achievements.views.page_not_found'
handler404 = 'achievements.views.page_not_found'
handler500 = 'achievements.views.server_error'
handler403 = 'achievements.views.permission_denied'
handler400 = 'achievements.views.bad_request'

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', RedirectView.as_view(url='/achievements')),
    url(r'^achievements/', include('achievements.urls', namespace="achievements")),
]

komendrinken/achievements/models/achievement.py
from django.db import models
from game import Game

class Achievement(models.Model):
    class Meta:
        app_label               = 'achievements'
    
    name        = models.CharField(max_length=30, unique=True)
    hint        = models.CharField(max_length=30)
    title       = models.CharField(max_length=30)
    players     = models.PositiveIntegerField()
    description = models.TextField(blank=True)
    explanation = models.TextField(blank=True)
    
    def __unicode__(self):
        """
        Returns a string representation of this object.

        @return string, string representation
        """
        return self.name
    
    def get_games(self):
        return Game.objects.filter(achievement=self.pk).count()

komendrinken/achievements/models/defaultimage.py
from django.db import models

# Imports for image handling
import StringIO
from PIL import Image, ExifTags
from django.core.files.base import ContentFile

class DefaultImage(models.Model):
    class Meta:
        app_label               = 'achievements'
    
    photo       = models.ImageField(blank=True)
    photo_thumb = models.ImageField(blank=True)
    use         = models.PositiveIntegerField(default=0)
    
    def save(self, *args, **kwargs):   
        if self.photo and not self.photo_thumb:
            image = Image.open(self.photo.file)
            
            # Rotate image depending on meta information about the orientation
            try:
                if image._getexif():
                    for orientation in ExifTags.TAGS.keys() : 
                        if ExifTags.TAGS[orientation]=='Orientation' : break 
                    exif=dict(image._getexif().items())

                    if   exif[orientation] == 3 : 
                        image=image.rotate(180, expand=True)
                    elif exif[orientation] == 6 : 
                        image=image.rotate(270, expand=True)
                    elif exif[orientation] == 8 : 
                        image=image.rotate(90, expand=True)
            except:
                print "ERROR: couldn't fetch Meta tags from the picture"

            w, h = image.size
            size = 512
            print w, h 
            if w == h:
                w, h = size, size
            elif w > h:
                w = int(w * (float(size)/h))
                h = size
            else:
                h = int(h * (float(size)/w))
                w = size
            print w, h 
            
            image = image.resize((w, h), Image.ANTIALIAS)
            print ((w-size)/2, (h-size)/2, size + (w-size)/2, size + (h-size)/2)
            image = image.transform((size, size), Image.EXTENT, ((w-size)/2, (h-size)/2, size + (w-size)/2, size + (h-size)/2))
            
            image_file_name = str(self.photo.file).replace('.', '_thumb.')
            image_file = ContentFile(image_file_name)
            image_file_name = image_file_name.split('/')[-1]
            image.save(image_file, 'JPEG', quality=90)
            self.photo_thumb.save(image_file_name, image_file, save=False)
            
        super(DefaultImage, self).save(*args, **kwargs)
            

komendrinken/achievements/models/group.py
from django.db import models
from competitor import Competitor

class Group(models.Model):
    class Meta:
        app_label               = 'achievements'
        ordering                = ['pk']
    
    name        = models.CharField(max_length=30)
    
    def __unicode__(self):
        """
        Returns a string representation of this object.

        @return string, string representation
        """
        return self.name
    
    def get_victories(self):
        victories = 0
        members = Competitor.objects.filter(group=self.pk)
        for member in members:
            victories += member.get_victories()
        
        return victories
        

komendrinken/achievements/models/vote.py
from django.db import models

class Vote(models.Model):
    class Meta:
        app_label               = 'achievements'
    
    nomination      = models.ForeignKey('Nomination')
    competitor      = models.ForeignKey('Competitor')

komendrinken/achievements/views/client.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from datetime import *
from django.db.models import Q
from achievements.models import *
from achievements.util import *
import sys

def get_competitor(request):
    competitor = Competitor.objects.filter(ip_source=getIP(request))
    if not competitor and get_active_competitor(request):
        competitor = get_active_competitor(request)
        competitor.ip_source = getIP(request)
        competitor.save()
    elif competitor:
        competitor = competitor[0]
        
    if competitor:
        set_active_competitor(request, competitor.pk)
        
    return competitor

def client(request):
    competitor = get_competitor(request)
    game = get_current_game()
    
    if not competitor:
        context = {
            "groups"            : Group.objects.all(),
        }

        return render(request, "achievements/client/signup.html", context)
    if game and game.status == "1" and not Vote.objects.filter(competitor=competitor.pk, nomination__game=game.pk):
        context = {
            "game"              : game,
            "competitor"        : competitor,
        }

        return render(request, "achievements/client/vote.html", context)
    else:
        if game:
            if game.status == "0":
                message = "Er staat een nieuw spel klaar, nog even geduld."
            elif game.status == "1":
                message = "Je hebt je stem voor het huidige spel al uitgebracht."
            elif game.status == "2":
                message = "De stemming voor het huidige spel is afgerond."
        else:
            message = "Er is momenteel geen stemming bezig."
        context = {
            "competitor"        : competitor,
            "message"           : message,
        }
        return render(request, "achievements/client/waiting.html", context)
    
def signUp(request):
    competitor = Competitor()
    error = None
    noForm = False
    admin = False
    
    try:
        competitor.name         = request.POST['name']
        if Competitor.objects.filter(name=request.POST['name']):
            error = "De naam die u heeft gekozen bestaat al, gelieve een andere te kiezen."
            
        competitor.group        = Group.objects.get(id=request.POST['group'])

        if "photo" in request.FILES:
            competitor.photo        = request.FILES["photo"]
                
        admin = request.POST['source'] == 'dashboard'
        
    except (KeyError):
        # Redisplay the form
        error = "Gelieve alle velden correct in te vullen!"

    if not admin:
        try:
            competitor.ip_source = getIP(request)
            if Competitor.objects.filter(ip_source=getIP(request)):
                error = "Dit apparaat staat reeds geregistreed. Klik <a href=\"/\">hier</a>."
                noForm = True
        except:
            error = "Probleem met het detecteren van het apparaat. Probeer later opnieuw"
            print "Unexpected error while parsing IP of source:", sys.exc_info()[0]
        
    if not error:
        try:
            competitor.save()
        except (IOError):
            error = "Gelieve een geldige foto te kiezen."
    
    if error:
        return render(request, "achievements/client/signup.html", {
            'competitor'    : competitor,
            'error_message' : error,
            'groups'        : Group.objects.all(),
            'noForm'        : noForm,
        })
    
    if admin:
        return HttpResponseRedirect(reverse('achievements:dashboard'))
    
    set_active_competitor(request, competitor.pk)
    
    # Always return an HttpResponseRedirect after successfully dealing
    # with POST data. This prevents data from being posted twice if a
    # user hits the Back button.
    return HttpResponseRedirect(reverse('achievements:home'))

def vote(request, game_id):
    game = get_current_game()

    if game and int(game.pk) == int(game_id):
        error = None
        admin = False
        
        try:
            admin = request.POST['source'] == 'dashboard'

        except (KeyError):
            admin = False
            
        try:
            if admin:
                competitor = Competitor.objects.get(pk=int(request.POST['competitor']))
            else:
                competitor = get_competitor(request)

            if competitor:
                if not Vote.objects.filter(competitor=competitor.pk, nomination__game=game.pk):

                    votes = []
                    for key in request.POST:
                        if key.startswith('player'):
                            nomination = Nomination.objects.get(pk=int(key.strip('player')))
                            votes += [Vote(nomination=nomination, competitor=competitor)]

                    if not votes:
                        error = "Selecteer 3 personen om je stem uit te brengen."
                    if len(votes) > 3:
                        error = "Je stem is ongeldig. Selecteer maximum 3 personen."
                        
                else:
                    error = "U heeft reeds een stem uitgebracht."
            else:
                error = "Kan de gebruiker niet detecteren."

        except (KeyError):
            error = "Gelieve alle velden correct in te vullen!"

        if error:
            return render(request, "achievements/client/vote.html", {
                "game"              : get_current_game(),
                "competitor"        : get_competitor(request),
                'error_message'     : error,
            })
        
        for vote in votes:
            vote.save()

        if admin:
            return HttpResponseRedirect(reverse('achievements:dashboard'))
        
        
    return HttpResponseRedirect(reverse('achievements:home'))

komendrinken/achievements/views/dashboard.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from datetime import *
from django.db.models import Q
from achievements.models import *
from achievements.util import *
import sys

@login_required
def dashboard(request):
    grouplist = []
    groups = Group.objects.all()
    
    for group in groups:
        grouplist.append((group, Competitor.objects.filter(group=group.pk)))
        
    game = get_current_game()

    context = {
        "grouplist"        : grouplist,
        "groups"           : groups,
        "achievements"     : Achievement.objects.all(),
        "game"             : game,
    }
    
    if game:
        if game.status == '0':
            return render(request, "achievements/dashboard/schedule_game.html", context)
        if game.status == '1':
            context["competitors"] = Competitor.objects.all().order_by("name")
            return render(request, "achievements/dashboard/voting.html", context)
        if game.status == '2':
            return render(request, "achievements/dashboard/winners.html", context)
        
    return render(request, "achievements/dashboard/new_game.html", context)

@login_required
def newGame(request, achievement_id):
    achievement = get_object_or_404(Achievement, pk=achievement_id)
    game = Game(achievement=achievement)
    game.save()
    return HttpResponseRedirect(reverse('achievements:dashboard'))

@login_required
def startVoting(request, game_id):
    game = get_object_or_404(Game, pk=game_id)
    game.start_voting()
    return HttpResponseRedirect(reverse('achievements:dashboard'))

@login_required
def scheduleVoting(request, game_id):
    game = get_object_or_404(Game, pk=game_id)
        
    try:
        start_vote = 0
        if 'start_vote' in request.POST and request.POST['start_vote']:
            offset = int(request.POST['start_vote'])
            start_vote = offset
            game.start_vote = datetime.now() + timedelta(0, offset * 60)
        if 'end_vote' in request.POST and request.POST['end_vote']:
            offset = int(request.POST['end_vote'])
            game.end_vote = datetime.now() + timedelta(0, (offset + start_vote) * 60)

        game.save()
        
    except:
        print "ERROR: something went wrong while scheduling start of the voting"
        
    return HttpResponseRedirect(reverse('achievements:dashboard'))

@login_required
def startGame(request, game_id):
    game = get_object_or_404(Game, pk=game_id)
    game.start_game()
    return HttpResponseRedirect(reverse('achievements:dashboard'))

@login_required
def endGame(request, game_id):
    game = get_object_or_404(Game, pk=game_id)
    
    winners = []
    for key in request.POST:
        if key.startswith('player'):
            winners += [int(key.strip('player'))]
            
    game.end_game(winners)
    return HttpResponseRedirect(reverse('achievements:dashboard'))  

komendrinken/achievements/views/error_page.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.utils.translation import ugettext as _

def page_not_found(request):
    error = '404'
    tekst = 'This page was not found.'
    context = {
        "error"                 : error,
        "error_text"            : tekst,
    }
    return render(request, "achievements/error_page.html", context)

def server_error(request):
    error = '500'
    tekst = 'Internal server error.'
    ticket = Ticket.objects.latest("date_created")
    context = {
        "error"                 : error,
        "error_text"            : tekst,
        "ticket"                : ticket.pk,
    }
    return render(request, "achievements/error_page.html", context)

def permission_denied(request):
    error = '403'
    tekst = 'Forbidden error.'
    context = {
        "error"                 : error,
        "error_text"            : tekst,
    }
    return render(request, "achievements/error_page.html", context)

def bad_request(request):
    error = '400'
    tekst = 'Bad request error.'
    context = {
        "error"                 : error,
        "error_text"            : tekst,
    }
    return render(request, "achievements/error_page.html", context)

komendrinken/achievements/views/presentation.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from datetime import *
from django.db.models import Q
from achievements.models import *
from achievements.util import *
import sys

@login_required
def presentation(request):
    game = get_current_game()
    
    if game and game.status == "1":
        grouplist = []
        groups = Group.objects.all()
    
        for group in groups:
            grouplist.append((group, Nomination.objects.filter(game=game.pk, competitor__group=group.pk)))
    
        context = {
            "game"              : game,
            "grouplist"         : grouplist,
        }
        return render(request, "achievements/presentation/voting.html", context)
    
    if game and game.status == "2":
        context = {
            "game"              : game,
        }
        return render(request, "achievements/presentation/game.html", context)
    
    game = get_last_game()
    if game and game.status == "3":
        context = {
            "game"              : game,
            "competitors"       : Competitor.objects.all(),
            "groups"            : Group.objects.all(),
        }
        return render(request, "achievements/presentation/winners.html", context)
    
    grouplist = []
    groups = Group.objects.all()
    
    for group in groups:
        grouplist.append((group, Competitor.objects.filter(group=group.pk, excluded=False)))

    context = {
        "grouplist"        : grouplist,
        "groups"           : groups,
        "game"             : game,
    }
    
    return render(request, "achievements/presentation/competitors.html", context)

komendrinken/achievements/templates/achievements/dashboard/base.html
{% extends "achievements/base.html" %}
{% load staticfiles %}

{% block title %}Dashboard{% endblock title %}

{% block heading %}
    <h1 class="text-center">
        Dashboard
    </h1>
{% endblock %}

{% block page %}
    <div class="row">
        <div class="col-md-3">
            <div class="row">
                <div class="col-md-1">
                </div>
                <div class="col-md-10">
                    <div class="page-header">
                        <h2>Deelnemers</h2>
                    </div>
                    {% for group in grouplist %}
                        <div class="panel-group" id="accordion" role="tablist">
                            <div class="panel panel-default">
                                <div class="panel-heading" role="tab" id="heading{{ group.0.pk }}">
                                    <h3 class="panel-title">
                                        <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse{{ group.0.pk }}" aria-expanded="false"
                                           aria-controls="collapse{{ group.0.pk }}">
                                            {{ group.0 }}
                                            <span class="badge pull-right">{{ group.1 | length }}</span>
                                        </a>
                                    </h3>
                                </div>
                                <div id="collapse{{ group.0.pk }}" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading{{ group.0.pk }}">
                                    <ul class="list-group">
                                        {% for competitor in group.1 %}
                                            <li class="list-group-item">
                                                {{ competitor }}
                                                {% if competitor.excluded %}
                                                    <span class="label label-warning ">Excluded</span>
                                                {% endif %}
                                                {% if competitor.blocked %}
                                                    <span class="label label-danger">Blocked</span>
                                                {% endif %}
                                                {% if competitor.photo_thumb %}
                                                    <a rel="popover" data-img="{{ competitor.photo_thumb.url }}" class="pull-right">
                                                        <span class="glyphicon glyphicon-picture" aria-hidden="true"></span>
                                                    </a>
                                                {% endif %}
                                        </li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                    <!-- Button trigger modal -->
                    <button type="button" class="btn btn-primary center-block" data-toggle="modal" data-target="#competitorModal">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Deelnemer toevoegen
                    </button>
                </div>
            </div>
        </div>
        <div class="col-md-9">
            <div class="row">
                <div class="col-md-1">
                </div>
                <div class="col-md-10">
                    <div class="page-header">
                        <h2>{% block header %}{% endblock %}</h2>
                    </div>
                    {% block content %}
                    {% endblock %}
                </div>  
            </div>
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="competitorModal" tabindex="-1" role="dialog" aria-labelledby="competitorModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h3 class="modal-title" id="competitorModalLabel">Nieuwe deelnemer</h3>
                </div>
                <div class="modal-body">
                    {% include "achievements/signupform.html" %}
                </div>
            </div>
        </div>
    </div>
{% endblock page %}

{% block script %}
    <script type="text/javascript">
        $('#competitorModal').on('show.bs.modal', function (event) {
            $(this).find('#source').val("dashboard")
        })
    </script>

    <script src="{% static 'general/js/validator.min.js' %}"></script>
    <script src="{% static 'general/js/fileUpload.js' %}"></script>
    <script src="{% static 'general/js/productsImageHover.js' %}"></script>
{% endblock %}

komendrinken/achievements/templates/achievements/dashboard/new_game.html
{% extends "achievements/dashboard/base.html" %}
{% load staticfiles %}

{% block header %}
    Kies het volgende spel
{% endblock %}

{% block content %}
    <div class="list-group">
        {% for achievement in achievements %}
            <a href="{% url 'achievements:newGame' achievement_id=achievement.pk %}" 
               class="list-group-item">
                <h4 class="list-group-item-heading">
                    {% if achievement.get_games == 0 %}
                        <span class="glyphicon glyphicon-star text-primary" aria-hidden="true"></span>
                    {% else %}
                        <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                    {% endif %}
                    {{ achievement }}
                    <span class="glyphicon glyphicon-chevron-right pull-right text-primary" aria-hidden="true"></span>
                </h4>
                <p class="list-group-item-text">
                    <strong>Titel: </strong>{{ achievement.title }} - 
                    <strong>Hint: </strong>{{ achievement.hint }} - 
                    <strong>Gespeeld: </strong>{{ achievement.get_games }}
                </p>
            </a>
        {% endfor %}
    </div>
{% endblock %}

komendrinken/achievements/templates/achievements/dashboard/schedule_game.html
{% extends "achievements/dashboard/base.html" %}
{% load staticfiles %}

{% block header %}
    Nieuw spel: {{ game }}
{% endblock %}
    
{% block content %}
    {% if game.start_vote %}
        <div class="alert alert-success" role="alert">
            Er is een timer geactiveerd. 
            De stemming begint automatisch over <span id="countdown"></span>.
        </div>
    {% endif %}
    <form   class="form-inline"
            action="{% url 'achievements:scheduleVoting' game_id=game.pk %}" 
            method="post" 
            data-toggle="validator">
        {% csrf_token %}

        <div class="form-group">
            <label for="start_vote">Start</label>
            <input type="number"
                   required
                   min=1 
                   class="form-control" 
                   id="start_vote" 
                   name="start_vote" 
                   placeholder="start in minuten">
        </div>
        <div class="form-group">
            <label for="end_vote">Einde</label>
            <input type="number" 
                   min=1 
                   class="form-control" 
                   id="end_vote" 
                   name="end_vote" 
                   placeholder="einde na start">
        </div>
        <button type="submit" class="btn btn-primary">
            Plan stemming
        </button>
        <a href="{% url 'achievements:startVoting' game_id=game.pk %}" role="button" class="btn btn-primary pull-right">
            Start stemming nu
        </a>
    </form>
{% endblock %}

{% block script %}
    {{ block.super }}
    <script src="{% static 'general/js/countdown.js' %}"></script>
    
    <script type="text/javascript">
        {% if game.start_vote %}
            countdown("{{ game.get_remaining_start }}");
        {% endif %}
    </script>
{% endblock %}

komendrinken/achievements/templates/achievements/dashboard/voting.html
{% extends "achievements/dashboard/base.html" %}
{% load staticfiles %}

{% block header %}
    Stemming: {{ game }}
{% endblock %}

{% block content %}
    {% if game.end_vote %}
        <div class="alert alert-success" role="alert">
            Er is een timer geactiveerd. 
            De stemming eindigt automatisch over <span id="countdown"></span>.
        </div>
    {% endif %}

    <div class="progress">
        <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="{{ game.get_voting_progress }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ game.get_voting_progress }}%">
            <span class="sr-only">{{ game.get_voting_progress }}% Complete</span>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <p>
                <strong>Aantal gestemde deelnemers:</strong> {{ game.get_number_voters }}<br>
                <strong>Aantal stemmen:</strong> {{ game.get_number_votes }}
            </p>
        </div>
        <div class="col-md-6">
            <button type="button" class="btn btn-default pull-right" data-toggle="modal" data-target="#votingModal">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Stem uitbrengen
            </button>
        </div>
    </div>
    <form   class="form-inline"
            action="{% url 'achievements:scheduleVoting' game_id=game.pk %}" 
            method="post" 
            data-toggle="validator">
        {% csrf_token %}
        <div class="form-group">
            <label for="end_vote">Einde</label>
            <input type="number" 
                   required
                   min=1 
                   class="form-control" 
                   id="end_vote" 
                   name="end_vote" 
                   placeholder="einde na start">
        </div>
        <button type="submit" class="btn btn-primary">
            Plan einde stemming
        </button>
        <a href="{% url 'achievements:startGame' game_id=game.pk %}" role="button" class="btn btn-primary pull-right">
            Eindig stemming nu
        </a>
    </form>

    <!-- Modal -->
    <div class="modal fade" id="votingModal" tabindex="-1" role="dialog" aria-labelledby="votingModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h3 class="modal-title" id="votingModalLabel">
                        Stem uitbrengen
                        <small>Je mag 3 personen aanduiden.</small>
                    </h3>
                </div>
                <div class="modal-body">
                    {% include "achievements/votingform.html" %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
    {{ block.super }}

    <script type="text/javascript">
        $('#votingModal').on('show.bs.modal', function (event) {
            $(this).find('#source').val("dashboard")
        })
    </script>

    <script src="{% static 'general/js/countdown.js' %}"></script>
    
    <script type="text/javascript">
        {% if game.end_vote %}
            countdown("{{ game.get_remaining_end }}");
        {% endif %}
    </script>
{% endblock %}

komendrinken/achievements/templates/achievements/dashboard/winners.html
{% extends "achievements/dashboard/base.html" %}
{% load staticfiles %}

{% block header %}
    Winnaars: {{ game }}
{% endblock %}

{% block content %}
    <p>Selecteer de winnaars van het spel.</p>
    <form   action="{% url 'achievements:endGame' game_id=game.pk %}" 
            method="post" 
            data-toggle="validator">
        {% csrf_token %}
        {% for player in game.get_players %}
            <div class="checkbox">
                <label>
                    <input type="checkbox" name="player{{ player.pk }}">
                    {{ player.competitor.name }} <small>({{player.competitor.group}})</small>
                </label>
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary">
            Bevestig winnaars
        </button>
    </form>

    <br>
    <br>
    <br>
    <dl class="dl-horizontal">
        <dt>Titel</dt>
        <dd>{{ game.achievement.title }}</dd>
        <dt>Beschrijving</dt>
        <dd>{{ game.achievement.description }}</dd>
        <dt>Uitleg</dt>
        <dd>{{ game.achievement.explanation }}</dd>
    </dl>
{% endblock %}