komendrinken/achievements/urls.py
from django.conf.urls import url

from achievements import views

urlpatterns = [
    url(r'^$', views.client, name="home"),
    url(r'^signup/$', views.signUp, name='handleSignUp'),
    url(r'^vote/(?P<game_id>\d+)/$', views.vote, name='handleVote'),
    
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^game/new/(?P<achievement_id>\d+)$', views.newGame, name='newGame'),
    url(r'^game/voting/(?P<game_id>\d+)$', views.startVoting, name='startVoting'),
    url(r'^game/schedule/(?P<game_id>\d+)$', views.scheduleVoting, name='scheduleVoting'),
    url(r'^game/start/(?P<game_id>\d+)$', views.startGame, name='startGame'),
    url(r'^game/end/(?P<game_id>\d+)$', views.endGame, name='endGame'),
    
    url(r'^presentation/$', views.presentation, name='presentation'),
]

komendrinken/komendrinken/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView

# Error pages
handler401 = 'achievements.views.page_not_found'
handler404 = 'achievements.views.page_not_found'
handler500 = 'achievements.views.server_error'
handler403 = 'achievements.views.permission_denied'
handler400 = 'achievements.views.bad_request'

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', RedirectView.as_view(url='/achievements')),
    url(r'^achievements/', include('achievements.urls', namespace="achievements")),
]

komendrinken/achievements/models/achievement.py
from django.db import models
from game import Game

class Achievement(models.Model):
    class Meta:
        app_label               = 'achievements'
    
    name        = models.CharField(max_length=30, unique=True)
    hint        = models.CharField(max_length=30)
    title       = models.CharField(max_length=30)
    players     = models.PositiveIntegerField()
    description = models.TextField(blank=True)
    explanation = models.TextField(blank=True)
    
    def __unicode__(self):
        """
        Returns a string representation of this object.

        @return string, string representation
        """
        return self.name
    
    def get_games(self):
        return Game.objects.filter(achievement=self.pk).count()

komendrinken/achievements/models/defaultimage.py
from django.db import models

# Imports for image handling
import StringIO
from PIL import Image, ExifTags
from django.core.files.base import ContentFile

class DefaultImage(models.Model):
    class Meta:
        app_label               = 'achievements'
    
    photo       = models.ImageField(blank=True)
    photo_thumb = models.ImageField(blank=True)
    use         = models.PositiveIntegerField(default=0)
    
    def save(self, *args, **kwargs):   
        if self.photo and not self.photo_thumb:
            image = Image.open(self.photo.file)
            
            # Rotate image depending on meta information about the orientation
            try:
                if image._getexif():
                    for orientation in ExifTags.TAGS.keys() : 
                        if ExifTags.TAGS[orientation]=='Orientation' : break 
                    exif=dict(image._getexif().items())

                    if   exif[orientation] == 3 : 
                        image=image.rotate(180, expand=True)
                    elif exif[orientation] == 6 : 
                        image=image.rotate(270, expand=True)
                    elif exif[orientation] == 8 : 
                        image=image.rotate(90, expand=True)
            except:
                print "ERROR: couldn't fetch Meta tags from the picture"

            w, h = image.size
            size = 512
            print w, h 
            if w == h:
                w, h = size, size
            elif w > h:
                w = int(w * (float(size)/h))
                h = size
            else:
                h = int(h * (float(size)/w))
                w = size
            print w, h 
            
            image = image.resize((w, h), Image.ANTIALIAS)
            print ((w-size)/2, (h-size)/2, size + (w-size)/2, size + (h-size)/2)
            image = image.transform((size, size), Image.EXTENT, ((w-size)/2, (h-size)/2, size + (w-size)/2, size + (h-size)/2))
            
            image_file_name = str(self.photo.file).replace('.', '_thumb.')
            image_file = ContentFile(image_file_name)
            image_file_name = image_file_name.split('/')[-1]
            image.save(image_file, 'JPEG', quality=90)
            self.photo_thumb.save(image_file_name, image_file, save=False)
            
        super(DefaultImage, self).save(*args, **kwargs)
            

komendrinken/achievements/models/group.py
from django.db import models
from competitor import Competitor

class Group(models.Model):
    class Meta:
        app_label               = 'achievements'
        ordering                = ['pk']
    
    name        = models.CharField(max_length=30)
    
    def __unicode__(self):
        """
        Returns a string representation of this object.

        @return string, string representation
        """
        return self.name
    
    def get_victories(self):
        victories = 0
        members = Competitor.objects.filter(group=self.pk)
        for member in members:
            victories += member.get_victories()
        
        return victories
        

komendrinken/achievements/models/vote.py
from django.db import models

class Vote(models.Model):
    class Meta:
        app_label               = 'achievements'
    
    nomination      = models.ForeignKey('Nomination')
    competitor      = models.ForeignKey('Competitor')

komendrinken/achievements/views/client.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from datetime import *
from django.db.models import Q
from achievements.models import *
from achievements.util import *
import sys

def get_competitor(request):
    competitor = Competitor.objects.filter(ip_source=getIP(request))
    if not competitor and get_active_competitor(request):
        competitor = get_active_competitor(request)
        competitor.ip_source = getIP(request)
        competitor.save()
    elif competitor:
        competitor = competitor[0]
        
    if competitor:
        set_active_competitor(request, competitor.pk)
        
    return competitor

def client(request):
    competitor = get_competitor(request)
    game = get_current_game()
    
    if not competitor:
        context = {
            "groups"            : Group.objects.all(),
        }

        return render(request, "achievements/client/signup.html", context)
    if game and game.status == "1" and not Vote.objects.filter(competitor=competitor.pk, nomination__game=game.pk):
        context = {
            "game"              : game,
            "competitor"        : competitor,
        }

        return render(request, "achievements/client/vote.html", context)
    else:
        if game:
            if game.status == "0":
                message = "Er staat een nieuw spel klaar, nog even geduld."
            elif game.status == "1":
                message = "Je hebt je stem voor het huidige spel al uitgebracht."
            elif game.status == "2":
                message = "De stemming voor het huidige spel is afgerond."
        else:
            message = "Er is momenteel geen stemming bezig."
        context = {
            "competitor"        : competitor,
            "message"           : message,
        }
        return render(request, "achievements/client/waiting.html", context)
    
def signUp(request):
    competitor = Competitor()
    error = None
    noForm = False
    admin = False
    
    try:
        competitor.name         = request.POST['name']
        if Competitor.objects.filter(name=request.POST['name']):
            error = "De naam die u heeft gekozen bestaat al, gelieve een andere te kiezen."
            
        competitor.group        = Group.objects.get(id=request.POST['group'])

        if "photo" in request.FILES:
            competitor.photo        = request.FILES["photo"]
                
        admin = request.POST['source'] == 'dashboard'
        
    except (KeyError):
        # Redisplay the form
        error = "Gelieve alle velden correct in te vullen!"

    if not admin:
        try:
            competitor.ip_source = getIP(request)
            if Competitor.objects.filter(ip_source=getIP(request)):
                error = "Dit apparaat staat reeds geregistreed. Klik <a href=\"/\">hier</a>."
                noForm = True
        except:
            error = "Probleem met het detecteren van het apparaat. Probeer later opnieuw"
            print "Unexpected error while parsing IP of source:", sys.exc_info()[0]
        
    if not error:
        try:
            competitor.save()
        except (IOError):
            error = "Gelieve een geldige foto te kiezen."
    
    if error:
        return render(request, "achievements/client/signup.html", {
            'competitor'    : competitor,
            'error_message' : error,
            'groups'        : Group.objects.all(),
            'noForm'        : noForm,
        })
    
    if admin:
        return HttpResponseRedirect(reverse('achievements:dashboard'))
    
    set_active_competitor(request, competitor.pk)
    
    # Always return an HttpResponseRedirect after successfully dealing
    # with POST data. This prevents data from being posted twice if a
    # user hits the Back button.
    return HttpResponseRedirect(reverse('achievements:home'))

def vote(request, game_id):
    game = get_current_game()

    if game and int(game.pk) == int(game_id):
        error = None
        admin = False
        
        try:
            admin = request.POST['source'] == 'dashboard'

        except (KeyError):
            admin = False
            
        try:
            if admin:
                competitor = Competitor.objects.get(pk=int(request.POST['competitor']))
            else:
                competitor = get_competitor(request)

            if competitor:
                if not Vote.objects.filter(competitor=competitor.pk, nomination__game=game.pk):

                    votes = []
                    for key in request.POST:
                        if key.startswith('player'):
                            nomination = Nomination.objects.get(pk=int(key.strip('player')))
                            votes += [Vote(nomination=nomination, competitor=competitor)]

                    if not votes:
                        error = "Selecteer 3 personen om je stem uit te brengen."
                    if len(votes) > 3:
                        error = "Je stem is ongeldig. Selecteer maximum 3 personen."
                        
                else:
                    error = "U heeft reeds een stem uitgebracht."
            else:
                error = "Kan de gebruiker niet detecteren."

        except (KeyError):
            error = "Gelieve alle velden correct in te vullen!"

        if error:
            return render(request, "achievements/client/vote.html", {
                "game"              : get_current_game(),
                "competitor"        : get_competitor(request),
                'error_message'     : error,
            })
        
        for vote in votes:
            vote.save()

        if admin:
            return HttpResponseRedirect(reverse('achievements:dashboard'))
        
        
    return HttpResponseRedirect(reverse('achievements:home'))

komendrinken/achievements/views/dashboard.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from datetime import *
from django.db.models import Q
from achievements.models import *
from achievements.util import *
import sys

@login_required
def dashboard(request):
    grouplist = []
    groups = Group.objects.all()
    
    for group in groups:
        grouplist.append((group, Competitor.objects.filter(group=group.pk)))
        
    game = get_current_game()

    context = {
        "grouplist"        : grouplist,
        "groups"           : groups,
        "achievements"     : Achievement.objects.all(),
        "game"             : game,
    }
    
    if game:
        if game.status == '0':
            return render(request, "achievements/dashboard/schedule_game.html", context)
        if game.status == '1':
            context["competitors"] = Competitor.objects.all().order_by("name")
            return render(request, "achievements/dashboard/voting.html", context)
        if game.status == '2':
            return render(request, "achievements/dashboard/winners.html", context)
        
    return render(request, "achievements/dashboard/new_game.html", context)

@login_required
def newGame(request, achievement_id):
    achievement = get_object_or_404(Achievement, pk=achievement_id)
    game = Game(achievement=achievement)
    game.save()
    return HttpResponseRedirect(reverse('achievements:dashboard'))

@login_required
def startVoting(request, game_id):
    game = get_object_or_404(Game, pk=game_id)
    game.start_voting()
    return HttpResponseRedirect(reverse('achievements:dashboard'))

@login_required
def scheduleVoting(request, game_id):
    game = get_object_or_404(Game, pk=game_id)
        
    try:
        start_vote = 0
        if 'start_vote' in request.POST and request.POST['start_vote']:
            offset = int(request.POST['start_vote'])
            start_vote = offset
            game.start_vote = datetime.now() + timedelta(0, offset * 60)
        if 'end_vote' in request.POST and request.POST['end_vote']:
            offset = int(request.POST['end_vote'])
            game.end_vote = datetime.now() + timedelta(0, (offset + start_vote) * 60)

        game.save()
        
    except:
        print "ERROR: something went wrong while scheduling start of the voting"
        
    return HttpResponseRedirect(reverse('achievements:dashboard'))

@login_required
def startGame(request, game_id):
    game = get_object_or_404(Game, pk=game_id)
    game.start_game()
    return HttpResponseRedirect(reverse('achievements:dashboard'))

@login_required
def endGame(request, game_id):
    game = get_object_or_404(Game, pk=game_id)
    
    winners = []
    for key in request.POST:
        if key.startswith('player'):
            winners += [int(key.strip('player'))]
            
    game.end_game(winners)
    return HttpResponseRedirect(reverse('achievements:dashboard'))  

komendrinken/achievements/views/error_page.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.utils.translation import ugettext as _

def page_not_found(request):
    error = '404'
    tekst = 'This page was not found.'
    context = {
        "error"                 : error,
        "error_text"            : tekst,
    }
    return render(request, "achievements/error_page.html", context)

def server_error(request):
    error = '500'
    tekst = 'Internal server error.'
    ticket = Ticket.objects.latest("date_created")
    context = {
        "error"                 : error,
        "error_text"            : tekst,
        "ticket"                : ticket.pk,
    }
    return render(request, "achievements/error_page.html", context)

def permission_denied(request):
    error = '403'
    tekst = 'Forbidden error.'
    context = {
        "error"                 : error,
        "error_text"            : tekst,
    }
    return render(request, "achievements/error_page.html", context)

def bad_request(request):
    error = '400'
    tekst = 'Bad request error.'
    context = {
        "error"                 : error,
        "error_text"            : tekst,
    }
    return render(request, "achievements/error_page.html", context)

komendrinken/achievements/views/presentation.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from datetime import *
from django.db.models import Q
from achievements.models import *
from achievements.util import *
import sys

@login_required
def presentation(request):
    game = get_current_game()
    
    if game and game.status == "1":
        grouplist = []
        groups = Group.objects.all()
    
        for group in groups:
            grouplist.append((group, Nomination.objects.filter(game=game.pk, competitor__group=group.pk)))
    
        context = {
            "game"              : game,
            "grouplist"         : grouplist,
        }
        return render(request, "achievements/presentation/voting.html", context)
    
    if game and game.status == "2":
        context = {
            "game"              : game,
        }
        return render(request, "achievements/presentation/game.html", context)
    
    game = get_last_game()
    if game and game.status == "3":
        context = {
            "game"              : game,
            "competitors"       : Competitor.objects.all(),
            "groups"            : Group.objects.all(),
        }
        return render(request, "achievements/presentation/winners.html", context)
    
    grouplist = []
    groups = Group.objects.all()
    
    for group in groups:
        grouplist.append((group, Competitor.objects.filter(group=group.pk, excluded=False)))

    context = {
        "grouplist"        : grouplist,
        "groups"           : groups,
        "game"             : game,
    }
    
    return render(request, "achievements/presentation/competitors.html", context)

komendrinken/achievements/templates/achievements/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
    <head>
        {% include "achievements/favicon.html" %}
        
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>Komen Drinken</title>

        <!-- Bootstrap -->
        <link href="{% static 'general/css/styles.css' %}" rel="stylesheet">

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body onload="{% block onload %}{% endblock onload %}">
        <div id="wrap">
            <div class="jumbotron">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12 visible-xs-block">
                            <img src="{% static 'general/img/logo.png' %}" width=400 class="img-responsive center-block"/>
                        </div>
                        <div class="hidden-xs">
                            <div class="col-md-4">
                                <img src="{% static 'general/img/logo.png' %}" width=400 class="img-responsive"/>
                            </div>
                            <div class="col-md-4">
                                {% block heading %}{% endblock %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% if competitor.blocked %}
                <div class="alert alert-danger" role="alert">
                    <p>
                        <strong>Uw deelname is momenteel geblokkeerd!</strong> <br>
                        Deelname onder naam van {{ competitor.name }}.
                    </p>
                </div>
            {% else %}
                <div class="container-fluid">
                    {% block page %}{% endblock page %}
                </div>
            {% endif %}
        </div> <!-- /#wrap -->

        <div id="footer">
            <div class="container-fluid">
                <table>
                    <tr>
                        <td id="copyright">
                            <p class="text-muted credit text-left">
                                <span class="glyphicon glyphicon-copyright-mark"></span> <a href="http://www.fb.com/ScoutingHoboken">Scouting Hoboken</a>
                            </p>
                        </td> <!-- /#copyright -->
                        <td id="address">
                            <p class="text-muted credit text-right">
                                {% if competitor.pk %}
                                    <a  href="#" data-toggle="modal" data-target="#competitorModal">
                                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                                    </a>
                                {% else %}
                                    <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                                {% endif %}
                            </p>
                        </td> <!-- /#address -->
                    </tr>
                </table> <!-- /.row -->
            </div>
        </div>
        

        <div class="modal fade" id="competitorModal" tabindex="-1" role="dialog" aria-labelledby="competitorModalLabel">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="competitorModalLabel">Deelnemer</h4>
                    </div>
                    <div class="modal-body">
                        <p>
                            <strong>Naam: </strong>{{ competitor.name }}<br>
                            <strong>Groep: </strong>{{ competitor.group }}<br>
                            <strong>IP: </strong>{{ competitor.ip_source }}
                        </p>
                        {% if competitor.photo_thumb %}
                            <img src="{{ competitor.photo_thumb.url }}" class="img-responsive center-block">
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>

        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <script src="{% static 'general/js/bootstrap.js' %}"></script>
        {% block script %}{% endblock %}
    </body>
</html>

komendrinken/achievements/templates/achievements/error_page.html
{% extends "achievements/base.html" %}
{% load staticfiles %}

{% block title %}No active game{% endblock title %}

{% block page %}
<div class="container">

    <h3 class="text-center">
        Er ging iets mis.
    </h3>
    <br>
    <br>
    <a href="/" role="button" class="btn btn-primary btn-lg center-block" style="margin-left: 50px; margin-right: 50px;">
        <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span> 
        Start opnieuw
    </a>
    <br>
    <br>
    <p><small>{{ error }}</small> {{ error_text }}</p>
</div> <!-- /container -->
{% endblock page %}

komendrinken/achievements/templates/achievements/favicon.html
{% load staticfiles %}

<link rel="apple-touch-icon" sizes="57x57" href="{% static 'general/img/favicons/apple-touch-icon-57x57.png' %}">
<link rel="apple-touch-icon" sizes="60x60" href="{% static 'general/img/favicons/apple-touch-icon-60x60.png' %}">
<link rel="apple-touch-icon" sizes="72x72" href="{% static 'general/img/favicons/apple-touch-icon-72x72.png' %}">
<link rel="apple-touch-icon" sizes="76x76" href="{% static 'general/img/favicons/apple-touch-icon-76x76.png' %}">
<link rel="apple-touch-icon" sizes="114x114" href="{% static 'general/img/favicons/apple-touch-icon-114x114.png' %}">
<link rel="apple-touch-icon" sizes="120x120" href="{% static 'general/img/favicons/apple-touch-icon-120x120.png' %}">
<link rel="apple-touch-icon" sizes="144x144" href="{% static 'general/img/favicons/apple-touch-icon-144x144.png' %}">
<link rel="apple-touch-icon" sizes="152x152" href="{% static 'general/img/favicons/apple-touch-icon-152x152.png' %}">
<link rel="apple-touch-icon" sizes="180x180" href="{% static 'general/img/favicons/apple-touch-icon-180x180.png' %}">
<link rel="icon" type="image/png" href="{% static 'general/img/favicons/favicon-32x32.png" sizes="32x32' %}">
<link rel="icon" type="image/png" href="{% static 'general/img/favicons/android-chrome-192x192.png' %}" sizes="192x192">
<link rel="icon" type="image/png" href="{% static 'general/img/favicons/favicon-96x96.png" sizes="96x96' %}">
<link rel="icon" type="image/png" href="{% static 'general/img/favicons/favicon-16x16.png" sizes="16x16' %}">
<link rel="manifest" href="{% static 'general/img/favicons/manifest.json' %}">
<link rel="mask-icon" href="{% static 'general/img/favicons/safari-pinned-tab.svg' %}" color="#e62020">
<meta name="msapplication-TileColor" content="#da532c' %}">
<meta name="msapplication-TileImage" content="{% static 'general/img/favicons/mstile-144x144.png' %}">
<meta name="theme-color" content="#ffffff">

komendrinken/achievements/templates/achievements/signupform.html
<form id="signUpForm" class="form-signin" action="{% url 'achievements:handleSignUp' %}" method="post" data-toggle="validator" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
        <label for="name" class="sr-only">Naam</label>
        <input type="text" id="name" name="name" class="form-control" placeholder="Naam" value="{{ competitor.name }}" required autofocus>
    </div>
    <div class="form-group">
        <label for="language" class="sr-only">Groep</label>
        <select type="text" class="form-control" id="group" name="group" value="{{ competitor.group }}" required>
        {% if not competitor.group %}
            <option disabled selected value="">-- selecteer je scoutsgroep --</option>
        {% endif %}
        {% for group in groups %}
            <option value="{{ group.pk }}">{{ group }}</option>
        {% endfor %}
        </select>
    </div>
    <div class="form-group">
        <label for="document" class="sr-only control-label">Photo</label>
        <div class="input-group">
            <span class="input-group-btn">
                <span class="btn btn-primary btn-file">
                    Kies een foto&hellip; <input type="file" name="photo">
                </span>
            </span>
            <input type="text" class="form-control" readonly>
        </div>
    </div>
    <input type="hidden" id="source" name="source">

    <button class="btn btn-lg btn-primary btn-block disabled" type="submit">Deelnemen</button>
</form>

komendrinken/achievements/templates/achievements/votingform.html
<form id="signUpForm" 
      class="form-signin" 
      action="{% url 'achievements:handleVote' game_id=game.pk %}" 
      method="post" 
      data-toggle="validator">
    {% csrf_token %}
    
    {% if competitors %}
        <div class="form-group">
            <label for="language" class="sr-only">Groep</label>
            <select type="text" 
                    class="form-control" 
                    id="competitor" 
                    name="competitor" 
                    required
                    >
                <option disabled selected value="">-- selecteer de gebruiker --</option>
                {% for player in competitors %}
                    <option value="{{ player.pk }}">{{ player }}
                        {% if player.ip_source %}
                            [Mobile]
                        {% endif %}
                        {% if player.excluded %}
                            [Excluded]
                        {% endif %}
                        {% if player.blocked %}
                            [Blocked]
                        {% endif %}
                </option>
                {% endfor %}
            </select>
        </div>
    {% endif %}
    
    {% for nomination in game.get_nominations %}
        <div class="panel panel-default">
            <div class="panel-body">
                {% if nomination.competitor.photo_thumb %}
                    <img class="media-object img-responsive" 
                         src="{{nomination.competitor.photo_thumb.url}}" 
                         alt="picture of {{ nomination.competitor }}">
                {% endif %}
                <div class="checkbox">
                    <label>
                        <input type="checkbox" name="player{{ nomination.pk }}">
                        <strong>{{ nomination.competitor.name }}</strong> 
                        <small>{{nomination.competitor.group}}</small>
                    </label>
                </div>
            </div>
        </div>
    {% endfor %}

    <input type="hidden" id="source" name="source">

    <button class="btn btn-lg btn-primary btn-block disabled" type="submit">Stem uitbrengen</button>
</form>